name: reactive_preferences
description: Wrapper for shared_preferences which adds the ability to listen to preference changes.
version: 0.1.0-nullsafety
homepage: https://github.com/Johann13/reactive_preferences

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5
  rxdart: ^0.27.0
  flutter_async_builder: ^0.1.0-nullsafety
dev_dependencies:
  flutter_test:
    sdk: flutter
