name: reactive_preferences
description: Wrapper for shared_preferences which adds the ability to listen to preference changes.
version: 0.0.4+1
homepage: https://github.com/Johann13/reactive_preferences

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  rxdart: ^0.25.0
  flutter_async_builder: ^0.0.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter
